### ISSUE TITLE
Error: Unable to access jarfile atlassian-agent.jar

### ISSUE THREAD

**Issue by bmilioli** [beigi-reza/atlassian-software#1]
Hi, 
I am getting this error while trying to crack . Do you know how to solve this? 
I used this command: 
docker exec 520fa53a01a3 java -jar /atlassian-agent.jar -m email@gmail.com -o company-p jira -s BTF6-8BTF-6BB7-XD3B

and
docker exec 520fa53a01a3 java -jar atlassian-agent.jar -m email@gmail.com -o company-p jira -s BTF6-8BTF-6BB7-XD3B

**Comment by MahdiPeydai** [comment]
me too
